#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Feb 19, 2021 10:33:05 PM EST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

import NoteBookPomo_support
from tkinter import messagebox


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()

    NoteBookPomo_support.set_Tk_var()
    top = Pomodoro(root)
    NoteBookPomo_support.init(root, top)
    root.mainloop()


w = None


def create_Pomodoro(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Pomodoro(root, *args, **kwargs)' .'''
    global w, w_win, root
    # rt = root
    root = rt
    w = tk.Toplevel(root)
    NoteBookPomo_support.set_Tk_var()
    top = Pomodoro(w)
    NoteBookPomo_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Pomodoro():
    global w
    w.destroy()
    w = None


class Pomodoro:


    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.', background=_bgcolor)
        self.style.configure('.', foreground=_fgcolor)
        self.style.configure('.', font="TkDefaultFont")
        self.style.map('.', background=
        [('selected', _compcolor), ('active', _ana2color)])

        top.geometry("276x442+976+126")
        top.minsize(120, 1)
        top.maxsize(3004, 1901)
        top.resizable(1, 1)
        top.title("Pomodoro")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.messagebox = messagebox

        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
        [('selected', _compcolor), ('active', _ana2color)])
        self.TNotebook1 = ttk.Notebook(top)
        self.TNotebook1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.TNotebook1.configure(takefocus="")
        self.TNotebook1_t1 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t1, padding=3)
        self.TNotebook1.tab(0, text="Pomodoro", compound="left", underline="-1", )
        self.TNotebook1_t1.configure(background="#d9d9d9")
        self.TNotebook1_t1.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t1.configure(highlightcolor="black")
        self.TNotebook1_t2 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t2, padding=3)
        self.TNotebook1.tab(1, text="Stats", compound="left", underline="-1", )
        self.TNotebook1_t2.configure(background="#d9d9d9")
        self.TNotebook1_t2.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t2.configure(highlightcolor="black")
        self.TNotebook1_t3 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t3, padding=3)
        self.TNotebook1.tab(2, text="Settings", compound="none", underline="-1", )
        self.TNotebook1_t3.configure(background="#d9d9d9")
        self.TNotebook1_t3.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t3.configure(highlightcolor="black")

        self.Listbox1 = tk.Listbox(self.TNotebook1_t1)
        self.Listbox1.place(relx=0.0, rely=0.048, relheight=0.651
                            , relwidth=1.004)
        self.Listbox1.configure(background="#f4f4f4")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(foreground="#000000")
        self.Listbox1.configure(highlightbackground="#d9d9d9")
        self.Listbox1.configure(highlightcolor="black")
        self.Listbox1.configure(selectbackground="blue")
        self.Listbox1.configure(selectforeground="white")

        self.Start = tk.Button(self.TNotebook1_t1)
        self.Start.place(relx=0.037, rely=0.709, height=24, width=257)
        self.Start.configure(activebackground="#ececec")
        self.Start.configure(activeforeground="#000000")
        self.Start.configure(background="#d9d9d9")
        self.Start.configure(command=NoteBookPomo_support.start_timer)
        self.Start.configure(disabledforeground="#a3a3a3")
        self.Start.configure(foreground="#000000")
        self.Start.configure(highlightbackground="#d9d9d9")
        self.Start.configure(highlightcolor="#000000")
        self.Start.configure(pady="0")
        self.Start.configure(text='''Start Pomodoro!''')

        self.Delete = tk.Button(self.TNotebook1_t1)
        self.Delete.place(relx=0.037, rely=0.769, height=24, width=117)
        self.Delete.configure(activebackground="#ececec")
        self.Delete.configure(activeforeground="#000000")
        self.Delete.configure(background="#d9d9d9")
        self.Delete.configure(command=NoteBookPomo_support.delete)
        self.Delete.configure(disabledforeground="#a3a3a3")
        self.Delete.configure(foreground="#000000")
        self.Delete.configure(highlightbackground="#d9d9d9")
        self.Delete.configure(highlightcolor="black")
        self.Delete.configure(pady="0")
        self.Delete.configure(text='''Delete''')

        self.Button2 = tk.Button(self.TNotebook1_t1)
        self.Button2.place(relx=0.515, rely=0.769, height=24, width=127)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(command=NoteBookPomo_support.refresh)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Refresh''')

        self.Entry1 = tk.Entry(self.TNotebook1_t1)
        self.Entry1.place(relx=0.294, rely=0.841, height=60, relwidth=0.676)
        self.Entry1.configure(background="#f4f4f4")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="blue")
        self.Entry1.configure(selectforeground="white")

        self.Button1 = tk.Button(self.TNotebook1_t1)
        self.Button1.place(relx=0.037, rely=0.841, height=64, width=67)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=NoteBookPomo_support.add_item)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Add Item''')

        self.Listbox2 = tk.Listbox(self.TNotebook1_t2)
        self.Listbox2.place(relx=0.037, rely=0.024, relheight=0.438
                            , relwidth=0.93)
        self.Listbox2.configure(background="#f4f4f4")
        self.Listbox2.configure(disabledforeground="#a3a3a3")
        self.Listbox2.configure(font="TkFixedFont")
        self.Listbox2.configure(foreground="#000000")
        self.Listbox2.configure(highlightbackground="#d9d9d9")
        self.Listbox2.configure(highlightcolor="black")
        self.Listbox2.configure(selectbackground="blue")
        self.Listbox2.configure(selectforeground="white")

        self.Pomos_completed = tk.Label(self.TNotebook1_t2)
        self.Pomos_completed.place(relx=0.037, rely=0.481, height=41, width=253)
        self.Pomos_completed.configure(activebackground="#f9f9f9")
        self.Pomos_completed.configure(activeforeground="black")
        self.Pomos_completed.configure(background="#d9d9d9")
        self.Pomos_completed.configure(disabledforeground="#a3a3a3")
        self.Pomos_completed.configure(foreground="#000000")
        self.Pomos_completed.configure(highlightbackground="#d9d9d9")
        self.Pomos_completed.configure(highlightcolor="black")
        self.Pomos_completed.configure(text='''Pomodoros completed''')

        self.Breaks_taken = tk.Label(self.TNotebook1_t2)
        self.Breaks_taken.place(relx=0.037, rely=0.601, height=41, width=253)
        self.Breaks_taken.configure(activebackground="#f9f9f9")
        self.Breaks_taken.configure(activeforeground="black")
        self.Breaks_taken.configure(background="#d9d9d9")
        self.Breaks_taken.configure(disabledforeground="#a3a3a3")
        self.Breaks_taken.configure(foreground="#000000")
        self.Breaks_taken.configure(highlightbackground="#d9d9d9")
        self.Breaks_taken.configure(highlightcolor="black")
        self.Breaks_taken.configure(text='''Breaks taken today''')

        self.Items_completed = tk.Label(self.TNotebook1_t2)
        self.Items_completed.place(relx=0.037, rely=0.721, height=41, width=253)
        self.Items_completed.configure(activebackground="#f9f9f9")
        self.Items_completed.configure(activeforeground="black")
        self.Items_completed.configure(background="#d9d9d9")
        self.Items_completed.configure(disabledforeground="#a3a3a3")
        self.Items_completed.configure(foreground="#000000")
        self.Items_completed.configure(highlightbackground="#d9d9d9")
        self.Items_completed.configure(highlightcolor="black")
        self.Items_completed.configure(text='''Items Completed today''')

        self.Total_items_completed = tk.Label(self.TNotebook1_t2)
        self.Total_items_completed.place(relx=0.037, rely=0.841, height=41
                                         , width=253)
        self.Total_items_completed.configure(activebackground="#f9f9f9")
        self.Total_items_completed.configure(activeforeground="black")
        self.Total_items_completed.configure(background="#d9d9d9")
        self.Total_items_completed.configure(disabledforeground="#a3a3a3")
        self.Total_items_completed.configure(foreground="#000000")
        self.Total_items_completed.configure(highlightbackground="#d9d9d9")
        self.Total_items_completed.configure(highlightcolor="black")
        self.Total_items_completed.configure(text='''Items completed to date''')

        self.Spinbox1 = tk.Spinbox(self.TNotebook1_t3, from_=1.0, to=100.0)
        self.Spinbox1.place(relx=0.625, rely=0.048, relheight=0.046
                            , relwidth=0.165)
        self.Spinbox1.configure(activebackground="#f9f9f9")
        self.Spinbox1.configure(background="white")
        self.Spinbox1.configure(buttonbackground="#d9d9d9")
        self.Spinbox1.configure(disabledforeground="#a3a3a3")
        self.Spinbox1.configure(font="TkDefaultFont")
        self.Spinbox1.configure(foreground="black")
        self.Spinbox1.configure(highlightbackground="black")
        self.Spinbox1.configure(highlightcolor="black")
        self.Spinbox1.configure(insertbackground="black")
        self.Spinbox1.configure(selectbackground="blue")
        self.Spinbox1.configure(selectforeground="white")
        self.Spinbox1.configure(textvariable=NoteBookPomo_support.work_time)
        self.value_list = [1, 25, 15, 20, 30,]
        self.Spinbox1.configure(values=self.value_list)

        self.Label1 = tk.Label(self.TNotebook1_t3)
        self.Label1.place(relx=0.147, rely=0.048, height=21, width=124)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Change the work time.''')

        self.Label2 = tk.Label(self.TNotebook1_t3)
        self.Label2.place(relx=0.147, rely=0.144, height=21, width=124)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Change the break time.''')

        self.Spinbox2 = tk.Spinbox(self.TNotebook1_t3, from_=1.0, to=100.0)
        self.Spinbox2.place(relx=0.625, rely=0.144, relheight=0.046
                            , relwidth=0.165)
        self.Spinbox2.configure(activebackground="#f9f9f9")
        self.Spinbox2.configure(background="white")
        self.Spinbox2.configure(buttonbackground="#d9d9d9")
        self.Spinbox2.configure(disabledforeground="#a3a3a3")
        self.Spinbox2.configure(font="TkDefaultFont")
        self.Spinbox2.configure(foreground="black")
        self.Spinbox2.configure(highlightbackground="black")
        self.Spinbox2.configure(highlightcolor="black")
        self.Spinbox2.configure(insertbackground="black")
        self.Spinbox2.configure(selectbackground="blue")
        self.Spinbox2.configure(selectforeground="white")
        self.Spinbox2.configure(textvariable=NoteBookPomo_support.break_time)
        self.value_list = [1, 5, 10, 15,]
        self.Spinbox2.configure(values=self.value_list)

        self.menubar = tk.Menu(top, font="TkMenuFont", bg=_bgcolor, fg=_fgcolor)
        top.configure(menu=self.menubar)


if __name__ == '__main__':
    vp_start_gui()
